sudo: false
language: node_js
addons:
  apt:
    packages:
      - libgconf-2-4 # this is a package that cypress depends on, need to add
cache:
  directories:
    - ~/.npm
    - ~/.cache # adds directory that cypress is cached into, don't have to wait now that it's included
notifications:
  email: false
node_js: '10'
install: echo "install happens as part of setup"
script: npm run setup
after_script: npx codecov@3
branches:
  only: master
